### ISSUE TITLE
 line 55 of file 'demo_nurbs_surfae_point_projection.py'

### ISSUE THREAD

**Issue by shuyueW1991** [RoberAgro/nurbspy#1]
In demos  filecase,  line 55 of file 'demo_nurbs_surfae_point_projection.py'  where the 'curve' should be replaced by 'surface' to match the source code. I verify that the correction is working, otherwise it won't run.

**Comment by RoberAgro** [comment]
You are correct, thank you for the heads up! I corrected the file
